//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt1.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaneOsobowe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DaneOsobowe()
        {
            this.Pracownik = new HashSet<Pracownik>();
        }
    
        public int IdDaneOsobowe { get; set; }
        public string NrPesel { get; set; }
        public string NIP { get; set; }
        public string NrDowoduOsobistego { get; set; }
        public string StanCywilny { get; set; }
        public string TelefonKontaktowy { get; set; }
        public string AdresEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pracownik> Pracownik { get; set; }
    }
}
