//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt1.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SputnikkEntities : DbContext
    {
        public SputnikkEntities()
            : base("name=SputnikkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdresPracownik> AdresPracownik { get; set; }
        public virtual DbSet<DaneOsobowe> DaneOsobowe { get; set; }
        public virtual DbSet<Departament> Departament { get; set; }
        public virtual DbSet<Malzonek> Malzonek { get; set; }
        public virtual DbSet<Pracownik> Pracownik { get; set; }
        public virtual DbSet<RodzicPracownika> RodzicPracownika { get; set; }
        public virtual DbSet<Stanowisko> Stanowisko { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Umowa> Umowa { get; set; }
    }
}
