//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt1.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        public int IdPracownika { get; set; }
        public int NrAkt { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string Imie2 { get; set; }
        public string Plec { get; set; }
        public int IdRodzicaPracownika { get; set; }
        public int IdMalzonek { get; set; }
        public int IdUmowa { get; set; }
        public int IdDaneOsobowe { get; set; }
        public int IdDepartament { get; set; }
        public int IdStanowisko { get; set; }
        public int IdAdresPracownik { get; set; }
    
        public virtual AdresPracownik AdresPracownik { get; set; }
        public virtual DaneOsobowe DaneOsobowe { get; set; }
        public virtual Departament Departament { get; set; }
        public virtual Malzonek Malzonek { get; set; }
        public virtual RodzicPracownika RodzicPracownika { get; set; }
        public virtual Stanowisko Stanowisko { get; set; }
        public virtual Umowa Umowa { get; set; }
    }
}
